apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  labels:
    app: name 
spec:
  storageClassName: sc 
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
 

